// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"worker-proto-01/job"
)

// Injectors from wire.go:

func InitializeMultiplyJob(userParams map[string]float32) job.Job {
	multiplyJob := job.NewMultiplyJob(userParams)
	return multiplyJob
}
